### ISSUE TITLE
RedisCache returning reference

### ISSUE THREAD

**Issue by rajats-smpx** [smartprix/sm-utils#9] opened 2018-07-23 12:27 UTC
When Rediscache returns value from its own localcache -> it returns a reference instead of a cloned object/value

**Comment by rajats-smpx** [comment] 2018-07-24 06:17
getOrSet returning reference rather than the value that was set in RedisCache

### How to get the error
```
const redisCache = new RedisCache('test_getOrSet');
const testObj = {
	a: 2,
};
const results = [];
await Promise.map([0, 1, 2], async (i) => {
	const res = await redisCache.getOrSet('testing', async () => {
		await Promise.delay(2000);
		return testObj;
	});
	if (i === 0) {
		res.a = 3;
	}
	// should ideally push 3 for i=0 and 2 for rest values of i
	results.push(res);
});
console.log(results);
// should have logged [{a: 3}, {a: 2}, {a: 2}]
// outputs [{a: 3}, {a: 3}, {a: 3}]
```

**Comment by smartprix** [comment] 2018-07-24 06:45
RedisCache is supposed to return a reference when returning from local. That's why localCache is used to save time taken from cloning and fetching from redis. While an option can be added to return a copy, or it should be assumed that cache will return a reference.

**Comment by rohit-smpx** [comment] 2018-07-24 06:47
The local object should be cloned before returning. Because editing it is basically setting the value in the local cache.

**Comment by smartprix** [comment] 2018-07-24 06:57
It's supposed to be this way, because that's what a map would do. And this functionality is used to reduced time in many places.

For example

```js
const product = await Product.loadById(1); // uses rediscache internally
if (!product.specs) product.specs = await Product.getSpecs(); 
```

If we clone the object every time, cache would no longer be a low cost abstraction. And cloning some model objects might not even work as intended.

**Comment by rohit-smpx** [comment] 2018-07-24 07:40
This makes it inconsistent though, this is more like a hack than a feature (without any documentation).
The same function will return different values in different processes while using the same cache, depending on the order of execution.

**Comment by smartprix** [comment] 2018-08-01 12:50
This is the expected behavior though. A little strange, but price to pay for performance. I'll add a debug option to debug changes to local cache.

**Comment by smartprix** [comment] 2018-09-13 14:39
Debug option `logOnLocalWrite` added in version `2.15.2` https://github.com/smartprix/sm-utils/commit/30b7cfa76e124ab49c2f1bb3584d0b89795c0f3e

**Comment by rohit-smpx** [comment] 2018-09-15 07:27
The current implementation of `logOnLocalWrite` doesn't log mutations for nested objects or even arrays

**Comment by rohit-smpx** [comment] 2018-09-15 07:54
Could use this : https://github.com/ElliotNB/observable-slim

**Comment by smartprix** [comment] 2018-09-17 06:29
`micro-observer` looks good, but only 2 stars is kind of problematic. For now it looks good, so we can version lock it.

**Comment by rohit-smpx** [comment] 2018-11-05 13:11
Closing, logOnLocalWrites (https://github.com/smartprix/sm-utils/pull/25) can be used to check for these.

**Closed by rohit-smpx** 2018-11-05 13:11 UTC
Labels: redis-cache
